clear all, close all, clc

% Defines the optimisation problem. (x0 is initial point, lb is lower
% bound, ub is upper bound
problem = createOptimProblem('fmincon',...
                             'objective',@(x) my_function(x(1),x(2)), ...
                             'x0',[0 0],...
                             'lb',[-3 -3],...
                             'ub',[3 3])

% Specifies that the defined problem is to be solved using MatLab's
% simulated annealing function. Also, sets the temperature and the maximum
% number of iterations.
problem.solver = 'simulannealbnd';
problem.objective = @(x) my_function(x(1),x(2));
problem.options = saoptimset('OutputFcn', @simulatedAnnealingPointPlotter,...
                             'Display','iter',...
                             'InitialTemperature',10,...
                             'MaxIter', 400)
                         
[x,f] = simulannealbnd(problem) 
